### ISSUE TITLE
Criar contributors.md

### ISSUE THREAD

**Issue by icarodredd** [axemdev/AxemDev-Library#4]

**Comment by juletopi** [comment]
Ficarei responsável por esta task.

Criarei um CONTRIBUTION.md que ficará relacionado a documentação geral do repositório.

**Comment by juletopi** [comment]
O [pull-request](https://github.com/axemdev/AxemDev-Library/pull/6) foi criado, aguardando o merge.

**Comment by icarodredd** [comment]
> O [pull-request](https://github.com/axemdev/AxemDev-Library/pull/6) foi criado, aguardando o merge.

Obrigado, excelente trabalho!
