### ISSUE TITLE
Complementar readme.md

### ISSUE THREAD

**Issue by icarodredd** [axemdev/AxemDev-Library#5]
Colocar nossas stacks do projeto, explicar o nosso objetivo, que não temos relação com o dono dos cursos postados na plataforma e nem os hospedamos, apenas linkamos etc.

**Comment by juletopi** [comment]
Ficarei responsável por esta task.

"_Colocar nossas stacks do projeto, explicar o nosso objetivo, que não temos relação com o dono dos cursos postados na plataforma e nem os hospedamos, apenas linkamos etc._"

Farei todos os requisitos acima e mais algumas modificações além de relacionar a parte do CONTRIBUTION.md à documentação do repositório.

**Comment by juletopi** [comment]
Realizei o [pull-request](https://github.com/axemdev/AxemDev-Library/pull/9) com a complementação contendo as modificações sugeridas e algumas modificações a mais.

No aguardo do merge.
